const DISTRICT_ENUM = Object.freeze({
  AGRONOMIA: { key: 'AGRONOMIA', label: 'Agronomía'},
  ALMAGRO: { key: 'ALMAGRO', label: 'Almagro'},
  BALVANERA: { key: 'BALVANERA', label: 'Balvanera'},
	BARRACAS: {key: 'BARRACAS', label: 'Barracas'},
	BELGRANO: {key: 'BELGRANO', label: 'Belgrano'},
	BOEDO: {key: 'BOEDO', label: 'Boedo'},
	CABALLITO: {key: 'CABALLITO', label: 'Caballito'},
	CHACARITA: {key: 'CHACARITA', label: 'Chacarita'},
	COGHLAN: {key: 'COGHLAN', label: 'Coghlan'},
	COLEGIALES: {key: 'COLEGIALES', label: 'Colegiales'},
	CONSTITUCION: {key: 'CONSTITUCION', label: 'Constitución'},
	FLORES: {key: 'FLORES', label: 'Flores'},
	FLORESTA: {key: 'FLORESTA', label: 'Floresta'},
	LA_BOCA: {key: 'LA_BOCA', label: 'La Boca'},
	LA_PATERNAL: {key: 'LA_PATERNAL', label: 'La Paternal'},
	LINIERS: {key: 'LINIERS', label: 'Liniers'},
	MATADEROS: {key: 'MATADEROS', label: 'Mataderos'},
	MONTE_CASTRO: {key: 'MONTE_CASTRO', label: 'Monte Castro'},
	MONSERRAT: {key: 'MONSERRAT', label: 'Monserrat'},
	NUEVA_POMPEYA: {key: 'NUEVA_POMPEYA', label: 'Nueva Pompeya'},
	NUNEZ: {key: 'NUNEZ', label: 'Núñez'},
	PALERMO: {key: 'PALERMO', label: 'Palermo'},
	PARQUE_AVELLANEDA: {key: 'PARQUE_AVELLANEDA', label: 'Parque Avellaneda'},
	PARQUE_CHACABUCO: {key: 'PARQUE_CHACABUCO', label: 'Parque Chacabuco'},
	PARQUE_CHAS: {key: 'PARQUE_CHAS', label: 'Parque Chas'},
	PARQUE_PATRICIOS: {key: 'PARQUE_PATRICIOS', label: 'Parque Patricios'},
	PUERTO_MADERO: {key: 'PUERTO_MADERO', label: 'Puerto Madero'},
	RECOLETA: {key: 'RECOLETA', label: 'Recoleta'},
	RETIRO: {key: 'RETIRO', label: 'Retiro'},
	SAAVEDRA: {key: 'SAAVEDRA', label: 'Saavedra'},
	SAN_CRISTOBAL: {key: 'SAN_CRISTOBAL', label: 'San Cristóbal'},
	SAN_NICOLAS: {key: 'SAN_NICOLAS', label: 'San Nicolás'},
	SAN_TELMO: {key: 'SAN_TELMO', label: 'San Telmo'},
	VELEZ_SARSFIELD: {key: 'VELEZ_SARSFIELD', label: 'Vélez Sársfield'},
	VERSALLES: {key: 'VERSALLES', label: 'Versalles'},
	VILLA_CRESPO: {key: 'VILLA_CRESPO', label: 'Villa Crespo'},
	VILLA_PARQUE: {key: 'VILLA_PARQUE', label: 'Villa del Parque'},
	VILLA_DEVOTO: {key: 'VILLA_DEVOTO', label: 'Villa Devoto'},
	VILLA_MITRE: {key: 'VILLA_MITRE', label: 'Villa General Mitre'},
	VILLA_LUGANO: {key: 'VILLA_LUGANO', label: 'Villa Lugano'},
	VILLA_LURO: {key: 'VILLA_LURO', label: 'Villa Luro'},
	VILLA_ORTUZAR: {key: 'VILLA_ORTUZAR', label: 'Villa Ortúzar'},
	VILLA_PUEYRREDON: {key: 'VILLA_PUEYRREDON', label: 'Villa Pueyrredón'},
	VILLA_REAL: {key: 'VILLA_REAL', label: 'Villa Real'},
	VILLA_RIACHUELO: {key: 'VILLA_RIACHUELO', label: 'Villa Riachuelo'},
	VILLA_SANTA_RITA: {key: 'VILLA_SANTA_RITA', label: 'Villa Santa Rita'},
	VILLA_SOLDATI: {key: 'VILLA_SOLDATI', label: 'Villa Soldati'},
	VILLA_URQUIZA: {key: 'VILLA_URQUIZA', label: 'Villa Urquiza'}	
});

export default DISTRICT_ENUM;
